### PR TITLE
Small addition and fix in Mixin Module

### LINKED ISSUE #805: Validate type of argument for `@ModifyArg` mixins
Should be simple, inspection + quickfix.

### PR DESCRIPTION
**Pull request by LlamaLad7**
Adds parameter and return type checking for @ModifyArgs
Resolves outer class constructor param being required; it is now treated as part of the method's optional parameters

### CODE REVIEW

**Comment by LlamaLad7** [comment]
This validates the type arguments of `@ModifyArgs` mixins, not `@ModifyArg` mixins. I was initially planning to do `@ModifyArg` as well, but they get special treatment in that you can either take a single arg, or all the method's args, and I couldn't find a way to represent that with the `ParameterGroup`s currently in place.

**Review by RedNesto — CHANGES_REQUESTED** [review]
Could you add tests for ModifyArgs ?
The rest LGTM.

**Comment by LlamaLad7** [comment]
In the process of writing a test I discovered that the fix was inserting the fully-qualified `Args` type instead of using the import.
This is only reproduceable inside the test environment, and when using `runIde` it all works fine.
It appears that not using the `thin` version of the Mixin dependency fixes this (perhaps the thin version doesn't include that type?)
Would you rather I allow the test to insert the fully-qualified type, or depend on the non-thin version of Mixin?
Thanks.

**Comment by RedNesto** [comment]
I'd say use the non-thin version for now, but I'd like input from @DemonWav about this.

File: src/test/kotlin/platform/mixin/InvalidInjectorMethodSignatureFixTest.kt [hunk 1]
```diff
@@ -33,6 +33,7 @@ class InvalidInjectorMethodSignatureFixTest : BaseMixinTest() {
 
                     class MixedInSimple {
                         public void simpleMethod(String string, int i) {
+                            int i = Integer.parseInt("FF", 16);
```
Comment (RedNesto) [inline src/test/kotlin/platform/mixin/InvalidInjectorMethodSignatureFixTest.kt]: The variable should be called something else, `i` is already used as a parameter. I don't know if it can conflict with anything, just in case.

**Review by RedNesto — CHANGES_REQUESTED** [review]

File: src/test/kotlin/platform/mixin/InvalidInjectorMethodSignatureFixTest.kt (hunk 1 above)
Comment (LlamaLad7) [reply src/test/kotlin/platform/mixin/InvalidInjectorMethodSignatureFixTest.kt]: Whoops I didn't see that.

**Comment by DenWav** [comment]
That's interesting, iirc thin means it only includes the API classes, so it should be included. It's been a while though - @Mumfrey would know either way.

**Review by DenWav — APPROVED** [review]
I think this looks good to go.

**Review by RedNesto — APPROVED** [review]

**Review by Earthcomputer — APPROVED** [review]
